const Config: {
  LINK_COLOR: string,
  LINK_SELECTED_COLOR: string,
  LINK_ARROW_WIDTH: number,

  BORDER_WIDTH: number,
  NODE_WIDTH: number,
  NODE_HEIGHT: number,

  NODE_COLOR: string,
  NODE_DISABLED_COLOR: string,
  NODE_BORDER_COLOR: string,
  NODE_STROKE_WEIGHT: number,
  NODE_TEXT_COLOR: string,
  NODE_SELECTED_BORDER_COLOR: string,
  NODE_SELECTED_STROKE_WEIGHT: number,
  NODE_PADDING: number,
  NODE_MAX_INPUT: number,
  NODE_MAX_OUTPUT: number,
  NODE_IO_SIZE: number,
  NODE_IO_SPACING: number,

  NODE_CONNECTOR_COLOR: string,
  NODE_CONNECTOR_SELECTED_COLOR: string,
  NODE_CONNECTOR_BORDER_COLOR: string,
  NODE_CONNECTOR_HOVER_COLOR: string,

  NODE_IO_HOVER_COLOR: string,
  NODE_IO_CONNECTOR_COLOR: string,

  HIGHLIGHT_BORDER_COLOR: string,
  HIGHLIGHT_BG_COLOR: string,

  DOCK_WIDTH: number,
  DOCK_COLOR: string,
  DOCK_TITLE_COLOR: string,
  DOCK_BORDER_COLOR: string,
} = {
  LINK_COLOR: '#D0D0D0',
  LINK_SELECTED_COLOR: '#1565c0',
  LINK_ARROW_WIDTH: 4,

  BORDER_WIDTH: 5,
  NODE_WIDTH: 60,
  NODE_HEIGHT: 30,

  NODE_COLOR: '#DFE7ED',
  NODE_DISABLED_COLOR: '#89959F',
  NODE_BORDER_COLOR: '#B9C4D2',
  NODE_STROKE_WEIGHT: 0,
  NODE_TEXT_COLOR: '#89959F',
  NODE_SELECTED_BORDER_COLOR: '#1565c0',
  NODE_SELECTED_STROKE_WEIGHT: 1,
  NODE_PADDING: 5,
  NODE_MAX_INPUT: 5,
  NODE_MAX_OUTPUT: 2,
  NODE_IO_SIZE: 10,
  NODE_IO_SPACING: 5,

  NODE_CONNECTOR_COLOR: '#B9C5D1',
  NODE_CONNECTOR_SELECTED_COLOR: '#75C750',
  NODE_CONNECTOR_BORDER_COLOR: '#89959F',
  NODE_CONNECTOR_HOVER_COLOR: '#F86C03',

  NODE_IO_HOVER_COLOR: '#F86C03',
  NODE_IO_CONNECTOR_COLOR: '#4caf50',

  HIGHLIGHT_BORDER_COLOR: '#2196f3',
  HIGHLIGHT_BG_COLOR: 'rgba(33,150,243,.15)',

  DOCK_WIDTH: 160,
  DOCK_COLOR: '#F8F8F8',
  DOCK_TITLE_COLOR: '#8D8D8B',
  DOCK_BORDER_COLOR: '#E9E9E9',
};

export default Config;