declare const Config: {
    LINK_COLOR: string;
    LINK_SELECTED_COLOR: string;
    LINK_ARROW_WIDTH: number;
    BORDER_WIDTH: number;
    NODE_WIDTH: number;
    NODE_HEIGHT: number;
    NODE_COLOR: string;
    NODE_DISABLED_COLOR: string;
    NODE_BORDER_COLOR: string;
    NODE_STROKE_WEIGHT: number;
    NODE_TEXT_COLOR: string;
    NODE_SELECTED_BORDER_COLOR: string;
    NODE_SELECTED_STROKE_WEIGHT: number;
    NODE_PADDING: number;
    NODE_MAX_INPUT: number;
    NODE_MAX_OUTPUT: number;
    NODE_IO_SIZE: number;
    NODE_IO_SPACING: number;
    NODE_CONNECTOR_COLOR: string;
    NODE_CONNECTOR_SELECTED_COLOR: string;
    NODE_CONNECTOR_BORDER_COLOR: string;
    NODE_CONNECTOR_HOVER_COLOR: string;
    NODE_IO_HOVER_COLOR: string;
    NODE_IO_CONNECTOR_COLOR: string;
    HIGHLIGHT_BORDER_COLOR: string;
    HIGHLIGHT_BG_COLOR: string;
};
export default Config;
