export default {
  LINK_COLOR: '#D0D0D0',
  LINK_SELECTED_COLOR: '#1565c0',
  LINK_ARROW_WIDTH: 4,

  BORDER_WIDTH: 5,
  NODE_WIDTH: 60,
  NODE_HEIGHT: 30,

  NODE_COLOR: '#DFE7ED',
  NODE_DISABLED_COLOR: '#89959F',
  NODE_BORDER_COLOR: '#B9C4D2',
  NODE_STROKE_WEIGHT: 0,
  NODE_TEXT_COLOR: '#89959F',
  NODE_SELECTED_BORDER_COLOR: '#1565c0',
  NODE_SELECTED_STROKE_WEIGHT: 1,
  NODE_PADDING: 5,
  NODE_MAX_INPUT: 5,
  NODE_MAX_OUTPUT: 2,
  NODE_IO_SIZE: 10,
  NODE_IO_SPACING: 5,

  NODE_CONNECTOR_COLOR: '#B9C5D1',
  NODE_CONNECTOR_SELECTED_COLOR: '#75C750',
  NODE_CONNECTOR_BORDER_COLOR: '#89959F',
  NODE_CONNECTOR_HOVER_COLOR: '#F86C03',

  NODE_IO_HOVER_COLOR: '#F86C03',
  NODE_IO_CONNECTOR_COLOR: '#4caf50',

  HIGHLIGHT_BORDER_COLOR: '#2196f3',
  HIGHLIGHT_BG_COLOR: 'rgba(33,150,243,.15)',
};